apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: develop-2
  url: https://github.com/juleslatapy/kubernetes-formation
  secretRef:
    name: my-key-git